### ISSUE TITLE
Please add dnsseed main.seed.ionomy.nl

### ISSUE THREAD

**Issue by RdeWilde** [ionomy/ion#100]
https://github.com/ionomy/ion/blob/14c03a64a90ef7e8f8ae34b25c83ff6a353d5e36/src/chainparams.cpp#L82

Please add `main.seed.ionomy.nl`

**Comment by mitchellcash** [comment]
utACK

**Comment by mitchellcash** [comment]
@RdeWilde why don't you just add the changes to a pull request? I know you can do it ;)

**Comment by RdeWilde** [comment]
Because I don't know if it'll end up in the sherlock's repository. I also tried directly editing in Github but it seems to be disabled.

**Comment by mitchellcash** [comment]
Don't worry about Sherlock's directory. It's just a fork of this repo. This is still the main repo. Put the PR through

**Comment by RdeWilde** [comment]
https://github.com/ionomy/ion/pull/102

**Comment by RdeWilde** [comment]
Merged!
