### ISSUE TITLE
Node IP Address doesn't change in ion Network when changing node to new address

### ISSUE THREAD

**Issue by jpass022** [ionomy/ion#37]
I moved two of my master nodes to different VPS servers with a different IP addresses. The nodes are working fine, but they are still being reported as coming from previous severs that are no longer up... It's been over 12 hours since the server move and the reported IP:port for the two nodes is the old servers that are not up any more...

**Comment by pcminer** [comment]
I would rather have the node IP address cloaked, or have some option to hide it from the public wallet...Imho it is not a good idea to have these addresses in every wallet, for security reasons. Alternative would be to remove some part of the Master Node IP addresses in the MN tab.
