### ISSUE TITLE
Implement Travis CI

### ISSUE THREAD

**Issue by mitchellcash** [ionomy/ion#8]
Continuous integration FTW 💥

**Comment by SherlockStd** [comment]
I don't uderstand why you want to implement Travis CI ?

**Comment by RdeWilde** [comment]
To build and test it on different systems/configurationd

**Comment by SherlockStd** [comment]
I'm used to build and test manually but yes why not ;)

**Comment by RdeWilde** [comment]
@SherlockStd Both have an upside, you'll still need manual testing. For open source projects like this travis is free anyway :)

**Comment by SherlockStd** [comment]
Ok :smile:  I will test it on my next project if I think it's needed :+1:

**Comment by SherlockStd** [comment]
Working to implement Travis on this project :smile:

**Comment by IonomyGuy** [comment]
I agree with this. Just need to make the file for it

**Comment by SherlockStd** [comment]
I'm working on it, I'm about to finish :+1: 
This platform is REALLY AMAZING, why I did't know that before :heart_eyes:

**Comment by IonomyGuy** [comment]
Sounds Good

**Comment by SherlockStd** [comment]
Working !!!!
https://travis-ci.org/SherlockStd/ion/builds/131526138

**Comment by SherlockStd** [comment]
I'm going to make a PR :smile:

**Comment by SherlockStd** [comment]
Wow and +1 to Travis for totaly integration in Github :+1: !!

**Comment by SherlockStd** [comment]
Just waiting for the second build (verification purposes)

**Comment by SherlockStd** [comment]
Everything go in https://github.com/ionomy/ion/pull/5 ....
Someone know if it's possible to create a second separated PR ??

**Comment by IonomyGuy** [comment]
Yes on your local fork create a new Branch and place the update in that.

**Comment by SherlockStd** [comment]
I just see that x)
But it will include the non-merged commit :-1:

**Comment by RdeWilde** [comment]
Also add osx to travis and clang provider. You can add a matrix to include the right ones. I've setup the first lines of travis on my repo ion-1 though i did not finish the rest of it.

**Comment by SherlockStd** [comment]
Yeah I see you add clang in your file, I will add it too this evening :smile:

**Comment by mitchellcash** [comment]
Nice work @SherlockStd, Travis is an amazing tool!

If you make a separate Pull Request for Travis we can merge it into master (after testing from devs)

**Comment by SherlockStd** [comment]
I got it :computer: : 
https://github.com/ionomy/ion/pull/16
